# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'flights.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rflights.proto\x1a\x0c\x63ommon.proto\"\x95\x01\n\x04Info\x12\x19\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x0b.FlightData\x12!\n\x04seat\x18\t \x01(\x0e\x32\x13.common.common.Seat\x12,\n\npassengers\x18\x08 \x03(\x0e\x32\x18.common.common.Passenger\x12!\n\x04trip\x18\x13 \x01(\x0e\x32\x13.common.common.Trip\"\x98\x01\n\nFlightData\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12+\n\x0b\x66rom_flight\x18\r \x01(\x0b\x32\x16.common.common.Airport\x12)\n\tto_flight\x18\x0e \x01(\x0b\x32\x16.common.common.Airport\x12\x16\n\tmax_stops\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\x0c\n\n_max_stopsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flights_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFO']._serialized_start=32
  _globals['_INFO']._serialized_end=181
  _globals['_FLIGHTDATA']._serialized_start=184
  _globals['_FLIGHTDATA']._serialized_end=336
# @@protoc_insertion_point(module_scope)
