# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: return_flights.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'return_flights.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14return_flights.proto\x1a\x0c\x63ommon.proto\"\x9b\x01\n\x04Info\x12\x1f\n\x0bitineraries\x18\x03 \x03(\x0b\x32\n.Itinerary\x12,\n\npassengers\x18\x08 \x03(\x0e\x32\x18.common.common.Passenger\x12!\n\x04seat\x18\t \x01(\x0e\x32\x13.common.common.Seat\x12!\n\x04trip\x18\x13 \x01(\x0e\x32\x13.common.common.Trip\"\xce\x01\n\tItinerary\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12$\n\x0eoutboundFlight\x18\x04 \x01(\x0b\x32\x07.FlightH\x00\x88\x01\x01\x12\x15\n\x08maxStops\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12+\n\x0b\x66romAirport\x18\r \x01(\x0b\x32\x16.common.common.Airport\x12)\n\ttoAirport\x18\x0e \x01(\x0b\x32\x16.common.common.AirportB\x11\n\x0f_outboundFlightB\x0b\n\t_maxStops\"i\n\x06\x46light\x12\x13\n\x0b\x66romAirport\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x11\n\ttoAirport\x18\x03 \x01(\t\x12\x13\n\x0b\x61irlineCode\x18\x05 \x01(\t\x12\x14\n\x0c\x66lightNumber\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'return_flights_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFO']._serialized_start=39
  _globals['_INFO']._serialized_end=194
  _globals['_ITINERARY']._serialized_start=197
  _globals['_ITINERARY']._serialized_end=403
  _globals['_FLIGHT']._serialized_start=405
  _globals['_FLIGHT']._serialized_end=510
# @@protoc_insertion_point(module_scope)
